name: Publish page

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup git user
        uses: fregante/setup-git-user@v1
      - name: Install dependencies
        run: npm install
      - name: Ensure fresh build
        run: npm run clear
      - name: Build Website
        run: npm run deploy
